# Generated by Django 4.1.1 on 2022-09-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_allscore_kid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='children',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='children',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='allscore',
            table='accounts_children_scores',
        ),
        migrations.AlterModelTable(
            name='children',
            table='accounts_children',
        ),
        migrations.CreateModel(
            name='ShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shore_tokens', to='accounts.children')),
            ],
        ),
    ]
