# Generated by Django 4.1.1 on 2022-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_children_age_alter_children_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='age',
            field=models.IntegerField(),
        ),
    ]
