# Generated by Django 4.1.1 on 2022-09-15 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_children_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allscore',
            name='kid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='children_score', to='accounts.children'),
        ),
        migrations.AlterField(
            model_name='children',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to=settings.AUTH_USER_MODEL),
        ),
    ]
