# Generated by Django 4.1.1 on 2022-09-19 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_allscore_kid_alter_children_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='name',
        ),
        migrations.RemoveField(
            model_name='children',
            name='parent',
        ),
        migrations.AddField(
            model_name='children',
            name='children_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_children',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
    ]
