# Generated by Django 4.1.1 on 2022-09-19 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_children_children_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='children_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='children_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
