# Generated by Django 4.1.1 on 2022-09-19 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_children_children_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allscore',
            name='kid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='children_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
