# Generated by Django 4.1.1 on 2022-09-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_allscore_kid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allscore',
            name='kid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='children_score', to='accounts.children'),
        ),
    ]
