# Generated by Django 4.1.1 on 2022-09-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.course')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(choices=[('in_progress', 'In progress'), ('done', 'Done')], default='in_progress', max_length=50)),
                ('task_status', models.CharField(choices=[('in_progress', 'In progress'), ('done', 'Done')], default='in_progress', max_length=50)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.allscore')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.course')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.task')),
            ],
        ),
    ]
