# Generated by Django 4.1.1 on 2022-09-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_allscore_kid'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='course_status',
        ),
        migrations.AlterField(
            model_name='progress',
            name='children',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_total_score', to='accounts.allscore'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='assignments.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='assignments.course'),
        ),
    ]
