# Generated by Django 4.1.1 on 2022-09-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_progress_course_remove_progress_course_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='assignments.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assignments.course'),
        ),
    ]
