# Generated by Django 4.1.1 on 2022-09-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_children_age'),
        ('assignments', '0003_alter_progress_task_alter_task_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenCourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('finished_ad', models.DateTimeField(default=None, null=True)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rels', to='accounts.children')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_rels', to='assignments.course')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('in_progress', 'In progress'), ('done', 'Done')], default='in_progress', max_length=50)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_task_progress_rels', to='accounts.children')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='assignments.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
