# Generated by Django 4.1.1 on 2022-09-14 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_childrencourserelation_taskprogress_delete_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='created_ad',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 13, 59, 40, 91371)),
        ),
    ]
