# Generated by Django 4.1.1 on 2022-09-14 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_taskprogress_created_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='created_ad',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 14, 2, 21, 240593)),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='task_status',
            field=models.CharField(choices=[('assign', 'Assign'), ('in_progress', 'In progress'), ('done', 'Done')], default='assign', max_length=50),
        ),
    ]
