# Generated by Django 4.1.1 on 2022-09-15 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_alter_taskprogress_created_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='created_ad',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 11, 58, 59, 726672)),
        ),
    ]
