# Generated by Django 4.1.1 on 2022-09-15 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_alter_taskprogress_created_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='finished_ad',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='created_ad',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 16, 54, 19, 888966)),
        ),
    ]
