# Generated by Django 4.1.1 on 2022-09-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_alter_childrencourserelation_created_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
