# Generated by Django 4.1.1 on 2022-09-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0021_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(),
        ),
    ]
